version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:3.11-management
    hostname: rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBIT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_PASSWORD}
    ports:
      - "5672:5672"
      - "15672:15672"
    expose:
      - '15672'
    volumes:
      - rabbitmq:/var/lib/rabbitmq/
volumes:
  rabbitmq:
